"""add needed models

Revision ID: 2def2e3b42e3
Revises: 7c9163df4a10
Create Date: 2026-04-06 13:08:26.492943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2def2e3b42e3'
down_revision: Union[str, Sequence[str], None] = '7c9163df4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Family',
    sa.Column('name', sa.String(), nullable=False, comment='Family name or branch name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description or history of the family'),
    sa.Column('origin_place', sa.String(), nullable=True, comment='Origin place of the family'),
    sa.Column('founded_year', sa.Integer(), nullable=True, comment='Approximate year when family was founded'),
    sa.Column('ended_year', sa.Integer(), nullable=True, comment='If family line ended'),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_name', 'Family', ['name'], unique=False)
    op.create_index(op.f('ix_Family_founded_year'), 'Family', ['founded_year'], unique=False)
    op.create_index(op.f('ix_Family_name'), 'Family', ['name'], unique=False)
    op.create_table('Person',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'UNKNOWN', name='person_gender_enum'), nullable=False, comment='Gender of the person'),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('birth_month', sa.SmallInteger(), nullable=True),
    sa.Column('birth_day', sa.SmallInteger(), nullable=True),
    sa.Column('death_year', sa.SmallInteger(), nullable=True),
    sa.Column('death_month', sa.SmallInteger(), nullable=True),
    sa.Column('death_day', sa.SmallInteger(), nullable=True),
    sa.Column('birth_date_raw', sa.String(), nullable=True, comment="Original text-date (for example: 'April 1970')"),
    sa.Column('death_date_raw', sa.String(), nullable=True, comment="Original text-date (for example: 'April 1970')"),
    sa.Column('family_id', sa.String(), nullable=False, comment='Person family ID'),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.CheckConstraint('birth_day BETWEEN 1 AND 31 OR birth_day IS NULL'),
    sa.CheckConstraint('birth_month BETWEEN 1 AND 12 OR birth_month IS NULL'),
    sa.CheckConstraint('death_day BETWEEN 1 AND 31 OR death_day IS NULL'),
    sa.CheckConstraint('death_month BETWEEN 1 AND 12 OR death_month IS NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['Family.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'id')
    )
    op.create_index('idx_birth_full', 'Person', ['birth_year', 'birth_month', 'birth_day'], unique=False)
    op.create_index('idx_person_name', 'Person', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_Person_birth_year'), 'Person', ['birth_year'], unique=False)
    op.create_index(op.f('ix_Person_death_year'), 'Person', ['death_year'], unique=False)
    op.create_index(op.f('ix_Person_first_name'), 'Person', ['first_name'], unique=False)
    op.create_index(op.f('ix_Person_last_name'), 'Person', ['last_name'], unique=False)
    op.create_table('parent_child',
    sa.Column('parent_id', sa.String(), nullable=False, comment='Parent person ID'),
    sa.Column('child_id', sa.String(), nullable=False, comment='Child person ID'),
    sa.Column('relation_type', postgresql.ENUM('BIOLOGICAL', 'ADOPTED', 'STEP', name='person_relation_type_enum'), nullable=False, comment='Type of relation for the person'),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.CheckConstraint('parent_id <> child_id'),
    sa.ForeignKeyConstraint(['child_id'], ['Person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['Person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'id')
    )
    op.create_index('idx_pc_child', 'parent_child', ['child_id'], unique=False)
    op.create_index('idx_pc_parent', 'parent_child', ['parent_id'], unique=False)
    op.create_table('spouses',
    sa.Column('first_person_id', sa.String(), nullable=False),
    sa.Column('second_person_id', sa.String(), nullable=False),
    sa.Column('marriage_year', sa.SmallInteger(), nullable=True),
    sa.Column('marriage_month', sa.SmallInteger(), nullable=True),
    sa.Column('marriage_day', sa.SmallInteger(), nullable=True),
    sa.Column('divorce_year', sa.SmallInteger(), nullable=True),
    sa.Column('marriage_date_raw', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.CheckConstraint('first_person_id < second_person_id'),
    sa.CheckConstraint('first_person_id <> second_person_id'),
    sa.ForeignKeyConstraint(['first_person_id'], ['Person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_person_id'], ['Person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('first_person_id', 'second_person_id', 'id')
    )
    op.create_index('idx_spouse_first_person', 'spouses', ['first_person_id'], unique=False)
    op.create_index('idx_spouse_second_person', 'spouses', ['second_person_id'], unique=False)
    op.create_index(op.f('ix_spouses_marriage_year'), 'spouses', ['marriage_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spouses_marriage_year'), table_name='spouses')
    op.drop_index('idx_spouse_second_person', table_name='spouses')
    op.drop_index('idx_spouse_first_person', table_name='spouses')
    op.drop_table('spouses')
    op.drop_index('idx_pc_parent', table_name='parent_child')
    op.drop_index('idx_pc_child', table_name='parent_child')
    op.drop_table('parent_child')
    op.drop_index(op.f('ix_Person_last_name'), table_name='Person')
    op.drop_index(op.f('ix_Person_first_name'), table_name='Person')
    op.drop_index(op.f('ix_Person_death_year'), table_name='Person')
    op.drop_index(op.f('ix_Person_birth_year'), table_name='Person')
    op.drop_index('idx_person_name', table_name='Person')
    op.drop_index('idx_birth_full', table_name='Person')
    op.drop_table('Person')
    op.drop_index(op.f('ix_Family_name'), table_name='Family')
    op.drop_index(op.f('ix_Family_founded_year'), table_name='Family')
    op.drop_index('idx_family_name', table_name='Family')
    op.drop_table('Family')
    # ### end Alembic commands ###
