"""add test user model

Revision ID: 7c9163df4a10
Revises: fc8ecd6b3e28
Create Date: 2026-03-31 08:41:19.924322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9163df4a10'
down_revision: Union[str, Sequence[str], None] = 'fc8ecd6b3e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('email', sa.String(), nullable=False, comment='Persons email address'),
    sa.Column('is_acc_blocked', sa.Boolean(), nullable=False, comment='Flag for account blocking'),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Account_email'), 'Account', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Account_email'), table_name='Account')
    op.drop_table('Account')
    # ### end Alembic commands ###
