"""add test user model

Revision ID: fc8ecd6b3e28
Revises: dded7f72bf75
Create Date: 2026-03-31 08:36:25.904374

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fc8ecd6b3e28'
down_revision: Union[str, Sequence[str], None] = 'dded7f72bf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
