repos:
  # BASE HOOKS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # RUFF
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^server/app/infrastructure/db/migrations/

      - id: ruff-format
        exclude: ^server/app/infrastructure/db/migrations/

  # MYPY
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
      - id: mypy
        pass_filenames: false
        entry: mypy server/app
        args: [--config-file=server/pyproject.toml]
        additional_dependencies:
          - pydantic==2.6.4
          - types-pytz==2025.2.0.20250326

  # ESLINT (frontend)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^client/src/.*\.(js|ts|jsx|tsx)$
        args: ["--config", "./client/.eslintrc"]
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.3.3
          - globals@13.24.0
          - eslint-plugin-react@7.37.5
          - eslint-plugin-import@2.32.0
          - eslint-plugin-jsx-a11y@6.10.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.6
          - "@typescript-eslint/parser@6.21.0"
          - "@typescript-eslint/eslint-plugin@6.21.0"
