"""add oauth model

Revision ID: 26a89e7607d6
Revises: eb5ff1d22b0a
Create Date: 2026-05-07 14:19:44.508489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a89e7607d6'
down_revision: Union[str, Sequence[str], None] = 'eb5ff1d22b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('account_id', sa.String(), nullable=False, comment='ID аккаунта владельца'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='Провайдер: google | telegram'),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False, comment='ID пользователя у провайдера (sub у Google, id у Telegram)'),
    sa.Column('id', sa.String(), nullable=False, comment='Entity identifier (UUID hex)'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Timestamp with timezone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider', name='uq_oauth_account_provider'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    op.create_index('idx_oauth_account_id', 'oauth_accounts', ['account_id'], unique=False)
    op.create_index('idx_oauth_provider_lookup', 'oauth_accounts', ['provider', 'provider_user_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_index('idx_oauth_provider_lookup', table_name='oauth_accounts')
    op.drop_index('idx_oauth_account_id', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
