"""make hashed password optional

Revision ID: 95432d1ae906
Revises: 26a89e7607d6
Create Date: 2026-05-07 14:49:04.759258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95432d1ae906'
down_revision: Union[str, Sequence[str], None] = '26a89e7607d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Account', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Bcrypt-hashed password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Account', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Bcrypt-hashed password')
    # ### end Alembic commands ###
