"""ref refresh tokens into diff table

Revision ID: afb60d661618
Revises: 62ce22365eb0
Create Date: 2026-05-04 11:19:37.688537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb60d661618'
down_revision: Union[str, Sequence[str], None] = '62ce22365eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Account', 'refresh_token')
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.add_column('Account', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Hashed refresh token stored server-side for rotation validation'))
    # ### end Alembic commands ###
