"""

Revision ID: c12b268d457a
Revises: ccbd50eab5bd
Create Date: 2026-05-27 15:35:52.083996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12b268d457a'
down_revision: Union[str, Sequence[str], None] = 'ccbd50eab5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('is_public', sa.Boolean(), nullable=False, comment='is public Family'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Family', 'is_public')
    # ### end Alembic commands ###
