"""add email token

Revision ID: ccbd50eab5bd
Revises: 95432d1ae906
Create Date: 2026-05-08 14:50:16.462711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbd50eab5bd'
down_revision: Union[str, Sequence[str], None] = '95432d1ae906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('account_id', sa.String(), nullable=False, comment='ID аккаунта владельца токена'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex от raw токена — raw никогда не хранится'),
    sa.Column('token_type', sa.String(length=32), nullable=False, comment='Тип токена: verify_email | reset_password'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Время истечения токена'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='True = токен уже был использован (одноразовый)'),
    sa.Column('id', sa.String(), nullable=False, comment='Entity identifier (UUID hex)'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Timestamp with timezone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_et_account_type', 'email_tokens', ['account_id', 'token_type'], unique=False)
    op.create_index('idx_et_token_hash', 'email_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_et_token_hash', table_name='email_tokens')
    op.drop_index('idx_et_account_type', table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
