from __future__ import annotations

from typing import Protocol

from domain.entities.permission import (
    AccountRoleEntity,
    PermissionEntity,
    RoleEntity,
    RolePermissionEntity,
)


class PermissionRepository(Protocol):
    async def get_all(self) -> list[PermissionEntity]: ...

    async def get_by_codename(self, codename: str) -> PermissionEntity | None: ...

    async def create(self, permission: PermissionEntity) -> PermissionEntity: ...

    async def remove_all(self) -> None: ...


class RoleRepository(Protocol):
    async def get_all(self) -> list[RoleEntity]: ...

    async def get_by_name(self, name: str) -> RoleEntity | None: ...

    async def get_with_permissions(self, name: str) -> RoleEntity | None: ...

    async def create(self, role: RoleEntity) -> RoleEntity: ...

    async def add_permission(self, role_permission: RolePermissionEntity) -> None: ...

    async def remove_all_permissions(self) -> None: ...

    async def remove_all(self) -> None: ...


class AccountRoleRepository(Protocol):
    async def get_permissions(self, account_id: str) -> frozenset[str]: ...

    async def get_role_name(self, account_id: str) -> str | None: ...

    async def create(self, account_role: AccountRoleEntity) -> None: ...

    async def update(self, account_role: AccountRoleEntity) -> None: ...

    async def exists(self, account_id: str) -> bool: ...
