"""update account model

Revision ID: 0377880a7a54
Revises: d63177b746ad
Create Date: 2026-04-14 17:43:43.857538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0377880a7a54'
down_revision: Union[str, Sequence[str], None] = 'd63177b746ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account', sa.Column('hashed_password', sa.String(), nullable=False, comment='Bcrypt-hashed password'))
    op.add_column('Account', sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Flag for email verification'))
    op.add_column('Account', sa.Column('refresh_token', sa.String(), nullable=True, comment='Hashed refresh token stored server-side for rotation validation'))
    op.alter_column('Account', 'email',
               existing_type=sa.VARCHAR(),
               comment="Person's email address",
               existing_comment='Persons email address',
               existing_nullable=False)
    op.drop_index(op.f('ix_Account_email'), table_name='Account')
    op.create_index(op.f('ix_Account_email'), 'Account', ['email'], unique=True)
    op.create_index('idx_account_email', 'Account', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_email', table_name='Account')
    op.drop_index(op.f('ix_Account_email'), table_name='Account')
    op.create_index(op.f('ix_Account_email'), 'Account', ['email'], unique=False)
    op.alter_column('Account', 'email',
               existing_type=sa.VARCHAR(),
               comment='Persons email address',
               existing_comment="Person's email address",
               existing_nullable=False)
    op.drop_column('Account', 'refresh_token')
    op.drop_column('Account', 'is_verified')
    op.drop_column('Account', 'hashed_password')
    # ### end Alembic commands ###
