"""

Revision ID: 75cecbd9580d
Revises: 7846b19caafe
Create Date: 2026-04-11 12:54:27.786957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cecbd9580d'
down_revision: Union[str, Sequence[str], None] = '7846b19caafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('email', sa.String(), nullable=False, comment='Persons email address'),
    sa.Column('is_acc_blocked', sa.Boolean(), nullable=False, comment='Flag for account blocking'),
    sa.Column('id', sa.String(), nullable=False, comment='Identifier of the entity'),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False, comment='Entity creation date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Account_email'), 'Account', ['email'], unique=False)
    op.alter_column('Person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_Account_email'), table_name='Account')
    op.drop_table('Account')
    # ### end Alembic commands ###
