"""add owner to family model

Revision ID: 892ec329830b
Revises: 75cecbd9580d
Create Date: 2026-04-12 20:15:26.763035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892ec329830b'
down_revision: Union[str, Sequence[str], None] = '75cecbd9580d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('owner_id', sa.String(), nullable=False, comment='Family owner account'))
    op.create_foreign_key(None, 'Family', 'Account', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Family', type_='foreignkey')
    op.drop_column('Family', 'owner_id')
    # ### end Alembic commands ###
