"""initial

Revision ID: d63177b746ad
Revises: dded7f72bf75
Create Date: 2026-04-13 17:08:31.740380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63177b746ad'
down_revision: Union[str, Sequence[str], None] = 'dded7f72bf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('owner_id', sa.String(), nullable=False, comment='Family owner account'))
    op.create_foreign_key(None, 'Family', 'Account', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('Person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'Family', type_='foreignkey')
    op.drop_column('Family', 'owner_id')
    # ### end Alembic commands ###
