# Addresses that postgres listen
listen_addresses = '*'

# Postgres port
port = 5432

# Cache size
shared_buffers = 4GB

# WAL buffer size
wal_buffers = 1GB

# WAL file max size
max_wal_size = 4GB

# WAL file min size
min_wal_size = 1GB

# How often to write WAL data from buffer
wal_writer_delay = 400ms

# Transaction considered as commited before flush WAL buffer
synchronous_commit = off

# How often the autovacuum daemon checks for tables that require vacuuming or analyzing
autovacuum_naptime = 5min

# Number of autovacuum worker processes that can run simultaneously
autovacuum_max_workers = 8

# Amount of memory allocated for internal sort operations and hash tables used by queries
work_mem = 16MB

# This parameter determines the maximum number of background worker processes that can be started by postgres
max_worker_processes = 8

# This option specifies the maximum number of parallel workers that can be used for query execution
max_parallel_workers = 8

# This setting controls how many parallel workers can be used per gather node in a query plan
max_parallel_workers_per_gather = 4

# This parameter defines the maximum number of parallel workers that can be used for maintenance operations, such as creating indexes or running vacuum commands
max_parallel_maintenance_workers = 4
